# Generated by Django 3.2.8 on 2021-10-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(default='www.google.com', max_length=255),
        ),
    ]
