# Generated by Django 3.2.8 on 2021-10-26 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('crew', models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255)),
                ('camera_type', models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('fujji', 'fujji'), ('others', 'others')], max_length=255)),
                ('photo', models.ImageField(upload_to='media/youtubers/%Y/%m/')),
                ('category', models.CharField(choices=[('code', 'code'), ('vlogs', 'vlogs'), ('cooking', 'cooking'), ('learning', 'learning')], max_length=255)),
                ('subs_count', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('video_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
