# Generated by Django 3.2.8 on 2021-11-07 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
